import Head from "next/head";
import Link from "next/link";
import React from "react";

const Layout = ({ children, title }) => {
  return (
    <React.Fragment>
      <Head>
        <title>{title ? title + " - Amazona" : "Amazona"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col min-h-screen justify-between">
        <header>
          <nav className="flex h-12 items-center justify-between shadow-md px-4">
            <Link href="/">
              <a className="text-lg font-bold">Amazona</a>
            </Link>
            <div className="space-x-5 font-bold">
              <Link href="/cart">
                <button className="px-2 py-1.5 hover:bg-gray-200 rounded-md">
                  Cart
                </button>
              </Link>
              <Link href="/login">
                <button className="px-2 py-1.5 hover:bg-gray-200 rounded-md">
                  Login
                </button>
              </Link>
            </div>
          </nav>
        </header>
        <main className="container m-auto mt-4 px-4">{children}</main>
        <footer className="flex h-10 justify-center items-center shadow-inner">
          <p>Amazona 2022</p>
        </footer>
      </div>
    </React.Fragment>
  );
};

export default Layout;
