import Head from "next/head";
import Link from "next/link";
import React, { useContext, useState, useEffect } from "react";
import { Store } from "../utils/Store";

const Layout = ({ children, title }) => {
  const { state, dispatch } = useContext(Store);
  const { cart } = state;

  const [cartItemsCount, setCartItemsCount] = useState(0);
  useEffect(() => {
    setCartItemsCount(cart.cartItems.reduce((a, c) => a + c.quantity, 0));
  }, [cart.cartItems]);

  console.log(cart);

  return (
    <React.Fragment>
      <Head>
        <title>{title ? title + " - Amazona" : "Amazona"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col min-h-screen justify-between">
        <header>
          <nav className="flex h-12 items-center justify-between shadow-md px-4">
            <Link href="/">
              <a className="text-lg font-bold">Amazona</a>
            </Link>
            <div className="space-x-5 font-bold">
              <Link href="/cart">
                <button className="px-2 py-1.5 hover:bg-gray-200 rounded-md">
                  Cart{" "}
                  {cartItemsCount > 0 && (
                    <span className="ml-1 rounded-full bg-red-600 px-2 py-1 text-xs font-bold text-white">
                      {cartItemsCount}
                    </span>
                  )}
                </button>
              </Link>
              <Link href="/login">
                <button className="px-2 py-1.5 hover:bg-gray-200 rounded-md">
                  Login
                </button>
              </Link>
            </div>
          </nav>
        </header>
        <main className="container m-auto mt-4 px-4">{children}</main>
        <footer className="flex h-10 justify-center items-center shadow-inner">
          <p>Amazona 2022</p>
        </footer>
      </div>
    </React.Fragment>
  );
};

export default Layout;
